version: '3'
services:
  salt-master:
    container_name: salt-master
    hostname: salt-master
    build:
      context: ""
      dockerfile: SaltMaster_DockerFile
    ports:
      - "4505:4505"
    environment:
      - HOSTNAME=salt-master
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: on-failure
  salt-minion1:
      container_name: salt-minion1
      hostname: salt-minion1
      links:
        - salt-master
      depends_on:
        - salt-master
      build:
        context: ""
        dockerfile: SaltMinion_DockerFile
      environment:
        - HOSTNAME=salt-minion1
      restart: on-failure
  salt-minion2:
        container_name: salt-minion2
        hostname: salt-minion2
        links:
          - salt-master
        depends_on:
          - salt-master
        build:
          context: ""
          dockerfile: SaltMinion_DockerFile1
        environment:
          - HOSTNAME=salt-minion2
        restart: on-failure
  salt-minion3:
        container_name: salt-minion3
        hostname: salt-minion3
        links:
          - salt-master
        depends_on:
          - salt-master
        build:
          context: ""
          dockerfile: SaltMinion_DockerFile
        environment:
          - HOSTNAME=salt-minion3
        restart: on-failure
