FROM vault

# Refer https://hub.docker.com/_/vault/ for details
ENV VAULT_ADDR=http://127.0.0.1:8200
ENV SKIP_SETCAP=TRUE
# ENV VAULT_DEV_ROOT_TOKEN_ID myroot
# ENV VAULT_DEV_LISTEN_ADDRESS 0.0.0.0:1234

COPY docker-entrypoint.sh .

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["server", "-dev" , "-dev-root-token-id=root" ]
